### ISSUE TITLE
Sketch 44.1 crashes when 'Clear palette' is used and then palette toggling happens

### ISSUE THREAD

**Issue by davewallace** [andrewfiorillo/sketch-palettes#48] opened 2017-05-31 04:43 UTC
Hi there,

First off, sweet plugin - thank you :)

Secondly, I crashed Sketch today by doing the following on macos Sierra (up-to-date):

 - Sketch is open (with 2 files open)
 - Checkout today's repo into ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Palettes
 - Sketch successfully loads the newly available Plugin
 - I exported a Global-only palette from file 1
 - I imported that palette into file 2, success
 - I realise I should've selected 'Document' and I use the 'Clear pelette' menu option
 - I remove the Global palette, the colour palette panel does not reflect this change
 - I try to toggle visibility on the colour palette panel to a closed state, and I try to re-expand it, in an attempt to see if the app's state just needs a kick
 - BAM!

Actually I am not certain whether it was the expand or collapse action that crashed, but it was one of them.

**Comment by andrewfiorillo** [comment] 2017-06-04 22:45
I can't seem to reproduce this bug now. This was a known issue previously, until the last release of Sketch, where those actions stopped causing a crash. Are you using the latest version of Sketch?

**Comment by davewallace** [comment] 2017-06-06 03:51
I wasn't updated - 44.1 was the reported version number though. It was bad update timing, I refused the updater just that same morning. I've now updated (still on 44.1 which is odd), and the issue continues - here's a screencast (excuse the chugginess, QuickTime very slow for some reason): https://drive.google.com/file/d/0B1dgdFJOLjqweTRuXzVwampDZU0/view?usp=sharing

Also, this repo was a fresh clone on the same day (last Friday) without having ever installed it before, so I wouldn't have any previous install history (I'm pretty new to Sketch).

**Comment by andrewfiorillo** [comment] 2017-06-06 14:50
Ok, I was able to reproduce it. It only happens when clearing, not loading I believe. I've been trying to figure out how to update the color picker while it is open, but haven't had much luck. That being the case, a quick fix for this might be to just close the popover when the palette is cleared, preventing the actions that cause the crash, since you currently have to close and re-open the color picker to see the changes reflected anyway.

**Comment by andrewfiorillo** [comment] 2017-06-06 17:56
Ok, I went ahead and implemented closing the popover when a palette is cleared or loaded. If you grab the latest release, you shouldn't be able to trigger the crash now. Going to go ahead and close this ticket.

**Closed as completed by andrewfiorillo** 2017-06-06 17:56 UTC
Labels: Bug, Fixed
