### ISSUE TITLE
Crashes Sketch 56.3

### ISSUE THREAD

**Issue by mmai35** [andrewfiorillo/sketch-palettes#87] opened 2019-08-08 15:44 UTC
Loading Palettes just crashes Sketch

**Comment by andrewfiorillo** [comment] 2019-08-08 21:01
I just checked it out, and I was not able to reproduce the issue. Could you double-check you are using the latest versions of Sketch and the plugin? And if so, and you still have the issue, could you share the palette you are trying to load?

**Comment by andrewfiorillo** [comment] 2019-08-12 15:23
I'm going to close this, as I can't reproduce.

**Closed as completed by andrewfiorillo** 2019-08-12 15:23 UTC
Labels: Can't Reproduce

**Comment by mmai35** [comment] 2019-08-12 15:35
Yeah it seems like specific sketch palette.



*Bach Mai*
Graphic Designer
Red Branch Media
(402) 249-2828

Get the Branch Working for You! <https://redbranchmedia.com/work-with-us/>

<http://blog.redbranchmedia.com/>
<https://www.linkedin.com/in/bach-mai-234608119/>
<https://redbranchmedia.com/>

**Comment by mmai35** [comment] 2019-08-16 15:11
Just wanted to mention that it was an issue with my google file stream and it
not fetching the file correctly and not the app itself. Sorry for the confusion!
Bach MaiGraphic Designer
Red Branch Media(402) 249-2828
Get the Branch Working for You!


Sent with Mixmax  





On Mon, Aug 12, 2019 3:35 PM, Bach Mai bach@redbranchmedia.com  wrote:
Yeah it seems like specific sketch palette.


Bach MaiGraphic Designer
Red Branch Media(402) 249-2828
Get the Branch Working for You!



On Mon, Aug 12, 2019 at 10:23 AM Andrew Fiorillo <notifications@github.com>
wrote:
Closed #87.
