### ISSUE TITLE
Crash when clearing color palette

### ISSUE THREAD

**Issue by bomberstudios** [andrewfiorillo/sketch-palettes#40] opened 2017-01-30 15:37 UTC
## Steps

1. Install the latest Sketch Palettes version
2. Create a new document, draw a Rectangle
3. download and unzip this file: [crash.sketchpalette.zip](https://github.com/andrewfiorillo/sketch-palettes/files/739379/crash.sketchpalette.zip)
3. Menu › Plugins › Sketch Palettes › Global Palettes › Load Palette... › find and load the palette file from previous point
4. select the Rectangle and open its Fill Color popover
5. expand the `Global Colors` (if it's not expanded already)
6. Menu › Plugins › Sketch Palettes › Global Palettes › Clear Palette
7. Collapse the `Global Colors` and expand them again = crash

**Comment by andrewfiorillo** [comment] 2017-01-30 16:03
Ok, I can reproduce. It happens any time you clear global colors (if you have any) while the color picker is open, and then collapse and expand the global colors section with the color picker still open.

Nothing in the console when it crashes. Any ideas?

Also, and potentially related: one thing I haven't been able to figure out is how to refresh the color picker UI while it is open, to show the new colors that were loaded. they only show up if you close and reopen the color picker (which makes sense, of course, since I'm only updating the data stored, not interacting with the UI). Do you know if that is possible?

**Comment by alandickinson** [comment] 2017-04-14 17:23
One possible fix may be to clear any selections before loading a palette file. That would close the color picker, but may also prevent the crash.

If there's no way to refresh the color picker while it's open, it actually may be a better ux to close it before loading, so it isn't left open in an outdated state.

**Comment by andrewfiorillo** [comment] 2017-04-17 15:08
Great suggestion. Better yet, would be just closing the color picker, since you might still want your selection. I just haven't been able to figure out how to dismiss the color picker yet (or any other UI changes there for that matter). But avoiding an even infrequent crash is probably worth losing your selection, until we can implement something else.

**Comment by alandickinson** [comment] 2017-04-23 22:28
I just poked around, and I don't see a way to only close the picker either 😞. No action is fired when I manually open and close it, so it doesn't seem like its accessible via an API.

**Comment by andrewfiorillo** [comment] 2017-04-24 14:18
@bomberstudios any chance you could point us in the right direction here?

**Comment by andrewfiorillo** [comment] 2017-05-22 20:33
This crash appears to have been fixed in the latest release. Closing the ticket.

**Closed as completed** 2017-05-22 20:33 UTC
Labels: Bug, Fixed
