### ISSUE TITLE
Sketch 3.4 issues

### ISSUE THREAD

**Issue by WhatsNewSaes** [andrewfiorillo/sketch-palettes#8] opened 2015-10-28 15:18 UTC
Everytime i try to load my palette nothing appears in my palette... could this be an issue with the recent update?

Love this plugin, btw!

**Comment by andrewfiorillo** [comment] 2015-10-28 16:16
Glad you like it! I tested the plugin with the new version 3.4, and it works for me. Can you send me the palette file, so I can troubleshoot?

**Comment by WhatsNewSaes** [comment] 2015-10-29 18:35
Ok, if it's not an issue with the current release, I'll try it a few more times and see if I can get it working. Thanks!

**Comment by simonhoye** [comment] 2015-11-02 03:53
@WhatsNewSaes I am having the same issue, did you get it working in the end?

**Comment by andrewfiorillo** [comment] 2015-11-03 21:07
I got an email from someone else having this problem. I wasn't able to reproduce it with his file though. Did you get yours working?

**Comment by gillisig** [comment] 2015-11-05 17:51
I had the same problem, but I had just installed the plugin and solved it with a restart.

**Comment by katywebster** [comment] 2015-11-11 15:10
Hi,
I'm having a similar problem. Sketch 3.4.1 isn't retaining the last palette I loaded. I'm pretty sure it's supposed to, you aren't expected to re-load a palette each time you open the Sketch file, am I right?
Thanks

**Comment by andrewfiorillo** [comment] 2015-11-11 15:55
Global colors should persist across all documents, even after quitting and restarting. Document colors should persist within the document only, but be available if you save the file, then reopen it again (even if you've quit Sketch in between).

It's strange, I was able to reproduce the bug once. But every time I try again is works as it is intended. I also tried the forthcoming 3.4.2, and it appears to work fine there. 

Perhaps try saving the file, and restarting Sketch to see if that helps? I'll keep digging around to see if I can reproduce the bug again.

**Comment by leehord** [comment] 2015-11-12 12:11
I had the same issue, when loading a palette in to Document Colors it did nothing, when loading in to Global Colors it crashed Sketch.

However I've since discovered that, if you don't have a layer selected it works fine :)

**Comment by andrewfiorillo** [comment] 2015-11-12 15:42
@leehord Well it definitely shouldn't crash either way. Can you share the sketch file and the palette file? Also, are you using 3.4 or 3.4.1? App store or from the website?

**Comment by leehord** [comment] 2015-11-13 10:04
I can’t seem to replicate the crash, I think it may have just been a co-incidence but it did co-incide with loading a palette. But I can confirm that when you have a layer selected the load action does not work.

**Comment by andrewfiorillo** [comment] 2015-11-16 15:45
@katywebster I was able to reproduce the bug you had which caused global colors to not persist after restarting Sketch. I just pushed a fix. Can you give it a shot?

**Closed as completed** 2015-11-16 16:54 UTC
Labels: Bug, Fixed

**Comment by katywebster** [comment] 2015-11-19 16:10
Hi,

Thanks, that works for me now!
