### ISSUE TITLE
Not working on 52.1?

### ISSUE THREAD

**Issue by libern** [andrewfiorillo/sketch-palettes#80] opened 2019-02-17 12:35 UTC
Not working on 52.1?

**Comment by andrewfiorillo** [comment] 2019-02-20 16:53
I'm not able to reproduce the bug. Can you check to make sure you are using the latest version of Sketch and the latest version of this plugin?

**Comment by mdestagnol** [comment] 2019-02-21 20:15
Also have a problem, the "Save Palette" doesn't do anything on 52.6

**Comment by mdestagnol** [comment] 2019-02-21 20:17
I rolled back 2.14 and it works properly. Seems like an issue with 2.21. Thx Andrew for making this useful plugin!

**Comment by andrewfiorillo** [comment] 2019-02-21 21:36
Ah sorry, I misread that as 53.1 (the current release when this was opened) not 52.1. The plugin been updated since to support newer versions of sketch, so the latest version of the plugin might not work for older versions of Sketch. But it sounds like you did what I was going to suggest - install a previous version of the plugin.

**Comment by andrewfiorillo** [comment] 2019-02-21 21:40
I'm going to go ahead and close this issue since the plugin itself is not intended to always be backwards compatible with older versions of Sketch. However, the palettes created in one version of Sketch/plugin should still be able to be imported in another.

**Closed as completed by andrewfiorillo** 2019-02-21 21:40 UTC
