### ISSUE TITLE
Colors are not saved between sessions

### ISSUE THREAD

**Issue by Niknam** [andrewfiorillo/sketch-palettes#20] opened 2016-05-20 14:25 UTC
When closing the Sketch document and reopening it, the color palette is reset to default and I have to reload the palette with my saved colors. I even recall the colors resetting during the same session.

**Comment by andrewfiorillo** [comment] 2016-05-20 14:27
Which version of Sketch are you running?

**Comment by Niknam** [comment] 2016-05-20 14:29
3.8.1, but I experienced the same issue while running 3.7.x as well.

**Comment by andrewfiorillo** [comment] 2016-05-20 14:48
Did you grab the latest version of this plugin?

**Comment by Niknam** [comment] 2016-05-20 15:05
I have v1.1 of this plugin. Is that the latest version?

**Comment by andrewfiorillo** [comment] 2016-05-20 15:13
Yeah, it is. I can't seem to reproduce with either version of Sketch (3.7.2 and 3.8.1). To clarify, is this using Document Colors, Global Colors, or both? Also, could you send me the palette file so I can take a look? fiorilloaj@gmail.com

**Comment by Niknam** [comment] 2016-05-20 15:16
I usually only change the Document Color, but once I accidentally changed the Global Colors. However, during the next session both the Global and Document Colors were reset to default. Sure, will send the palette file right away.

**Comment by chrischernoff** [comment] 2016-05-20 18:13
I'm on 3.7.2 with 1.1 and am having the same issue. [Here](https://github.com/andrewfiorillo/sketch-palettes/files/275190/app_colors.sketchpalette.zip) is the palette I've been using.

Documents don't retain document colors once they've been closed, and global colors are reset to my old global palette that was set by this plugin once Sketch is quit. I haven't attempted to replace my global palette in a while, so I suspect this is something with Sketch 3.7+

**Comment by andrewfiorillo** [comment] 2016-05-20 18:25
Weird. I'm running the same versions (3.7.2 and 1.1) as you. I just re-downloaded my plugin from Github to make sure it is the same. Using your palette file, I'm still not able to reproduce the bug. @chrischernoff could you provide the sketch file you are working with?

**Comment by chrischernoff** [comment] 2016-05-20 18:48
I think the version of the plugin I had was an _older_ version of 1.1. When looking in Plugins → Preferences, I saw 1.1. After viewing it in Finder I saw the date modified was ~11/27/15. Having seen your latest commit on here is 1/27/16, I uninstalled and reinstalled. Sure enough, the latest download has a date modified of 1/27/16. It works as expected now, although it still says 1.1 in Preferences → Plugins, so not sure what that's about.

Edit: Went digging in my trash to find the old uninstalled version. The version number in manifest.json is identical.

`"version": "1.1",`

**Comment by andrewfiorillo** [comment] 2016-05-20 19:00
Yeah, that's my fault. I merged a pull request from someone else when a bug popped up previously, and didn't update the version number. I appreciate you catching that!

**Comment by andrewfiorillo** [comment] 2016-05-20 19:02
@Niknam if you download the plugin again (version 1.2), I think the problem should be resolved. Let me know if that doesn't do the trick!

**Closed as completed** 2016-05-20 19:03 UTC
Labels: Bug, Fixed

**Comment by Niknam** [comment] 2016-05-20 20:29
@chrischernoff That was very observant. Thanks for the effort!
@andrewfiorillo 1.2 seems to do the trick! Thanks a lot for the quick replies! Much appreciated. :)

**Comment by chrischernoff** [comment] 2016-05-20 23:07
👍
